export  const SEARCH_REQUEST="SEARCH_MOVIE"
export  const SEARCH_SUCCESS="SEARCH_SUCCESS"
export  const SEARCH_FAILER="SEARCH_FAILER"

export  const MOVIEINFO_REQUEST="MOVIEINFO_MOVIE"
export  const MOVIEINFO_SUCCESS="MOVIEINFO_SUCCESS"
export  const MOVIEINFO_FAILER="MOVIEINFO_FAILER"

export  const MOSTPOPULAR_REQUEST="MOSTPOPULAR_MOVIE"
export  const MOSTPOPULAR_SUCCESS="MOSTPOPULAR_SUCCESS"
export  const MOSTPOPULAR_FAILER="MOSTPOPULAR_FAILER"


export  const MOVIESINTHEATRES_REQUEST="MOVIESINTHEATRES_MOVIE"
export  const MOVIESINTHEATRES_SUCCESS="MOVIESINTHEATRES_SUCCESS"
export  const MOVIESINTHEATRES_FAILER="MOVIESINTHEATRES_FAILER"


export  const HIGHESTRATED_REQUEST="HIGHESTRATED_MOVIE"
export  const HIGHESTRATED_SUCCESS="HIGHESTRATED_SUCCESS"
export  const HIGHESTRATED_FAILER="HIGHESTRATED_FAILER"

export  const KIDSMOVIES_REQUEST="KIDSMOVIES_MOVIE"
export  const KIDSMOVIES_SUCCESS="KIDSMOVIES_SUCCESS"
export  const KIDSMOVIES_FAILER="KIDSMOVIES_FAILER"

export  const BESTMOVIESFROM_REQUEST="BESTMOVIESFROM_MOVIE"
export  const BESTMOVIESFROM_SUCCESS="BESTMOVIESFROM_SUCCESS"
export  const BESTMOVIESFROM_FAILER="BESTMOVIESFROM_FAILER"

export  const BESTDRAMATHISYEAR_REQUEST="BESTDRAMATHISYEAR_MOVIE"
export  const BESTDRAMATHISYEAR_SUCCESS="BESTDRAMATHISYEAR_SUCCESS"
export  const BESTDRAMATHISYEAR_FAILER="BESTDRAMATHISYEAR_FAILER"

export  const TOMCRUISE_REQUEST="TOMCRUISE_MOVIE"
export  const TOMCRUISE_SUCCESS="TOMCRUISE_SUCCESS"
export  const TOMCRUISE_FAILER="TOMCRUISE_FAILER"

export  const HIGHESTCOMEDIES_REQUEST="HIGHESTCOMEDIES_MOVIE"
export  const HIGHESTCOMEDIES_SUCCESS="HIGHESTCOMEDIES_SUCCESS"
export  const HIGHESTCOMEDIES_FAILER="HIGHESTCOMEDIES_FAILER"